let icons = [
    

    '<i class="fa fa-comment-alt"></i>',
    '<i class="fa fa-envelope-open-text"></i>',
    '<i class="fa fa-map-marker-alt"></i>',
    '<i class="fa fa-search"></i>',
    '<i class="fa fa-quote-right"></i>',
    '<i class="fa fa-fill-drip"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-amazon"></i>',
    '<i class="fab fa-artstation"></i>',
    '<i class="fab fa-avianex"></i>',
    '<i class="fab fa-chrome"></i>',
    '<i class="fab fa-creative-commons"></i>',
    '<i class="fab fa-codepen"></i>',
    '<i class="fab fa-cc-jcb"></i>',
    '<i class="fab fa-slack-hash"></i>',
    '<i class="fab fa-speakap"></i>',
    '<i class="fab fa-stack-overflow"></i>',
    '<i class="fab fa-sticker-mule"></i>',
    
    '<i class="fa fa-comment-alt"></i>',
    '<i class="fa fa-envelope-open-text"></i>',
    '<i class="fa fa-map-marker-alt"></i>',
    '<i class="fa fa-search"></i>',
    '<i class="fa fa-quote-right"></i>',
    '<i class="fa fa-fill-drip"></i>',
    '<i class="fab fa-adn"></i>',
    '<i class="fab fa-amazon"></i>',
    '<i class="fab fa-artstation"></i>',
    '<i class="fab fa-avianex"></i>',
    '<i class="fab fa-chrome"></i>',
    '<i class="fab fa-creative-commons"></i>',
    '<i class="fab fa-codepen"></i>',
    '<i class="fab fa-cc-jcb"></i>',
    '<i class="fab fa-slack-hash"></i>',
    '<i class="fab fa-speakap"></i>',
    '<i class="fab fa-stack-overflow"></i>',
    '<i class="fab fa-sticker-mule"></i>',
]

let icons_copy=[]